#!/usr/bin/env python3
"""Generate remedies.py for NatureCure V2."""
import json, textwrap, os

OUTFILE = os.path.join(os.path.dirname(__file__), "remedies.py")

CATEGORIES = {
    "digestive": ["bloating","gas","indigestion","nausea","constipation","diarrhea","acid reflux","heartburn","stomach pain","stomach cramps","appetite loss","ibs","irritable bowel","leaky gut","food intolerance"],
    "sleep_stress": ["insomnia","anxiety","stress","nervousness","restlessness","sleep problems","trouble sleeping","poor sleep","racing thoughts","tension","panic","worry","overwhelm","burnout"],
    "immunity": ["frequent colds","weak immunity","flu","cold","sore throat","congestion","runny nose","sneezing","fever","infections","low immunity","getting sick often"],
    "pain_inflammation": ["headache","migraine","back pain","joint pain","muscle pain","inflammation","swelling","arthritis","chronic pain","body aches","neck pain","shoulder pain","knee pain","stiffness"],
    "respiratory": ["cough","shortness of breath","wheezing","bronchitis","chest congestion","sinus pressure","sinusitis","allergies","hay fever","nasal congestion","post nasal drip","asthma symptoms"],
    "energy_focus": ["fatigue","low energy","brain fog","poor concentration","lack of motivation","mental fatigue","drowsiness","lethargy","exhaustion","poor focus","memory problems","tiredness"],
    "skin": ["acne","eczema","dry skin","rash","itching","psoriasis","skin irritation","oily skin","dark spots","aging skin","wrinkles","skin inflammation","hives","redness"],
    "joint_muscle": ["joint stiffness","muscle cramps","muscle soreness","tendinitis","carpal tunnel","fibromyalgia","sciatica","bursitis","muscle weakness","muscle tension","sprain","strain"],
    "hair": ["hair loss","thinning hair","dandruff","dry hair","brittle hair","premature graying","slow hair growth","scalp issues"],
    "mood": ["depression","mood swings","irritability","sadness","low mood","seasonal affective","emotional imbalance","apathy"],
    "weight": ["weight gain","slow metabolism","water retention","belly fat","appetite control","cravings","overeating","binge eating"],
    "heart": ["high blood pressure","high cholesterol","poor circulation","palpitations","varicose veins","cold hands","cold feet"],
    "womens_health": ["period cramps","pms","menstrual pain","irregular periods","hot flashes","menopause","hormonal imbalance","breast tenderness","heavy periods","mood swings menstrual"],
    "liver_detox": ["liver support","hangover","detox","toxin buildup","fatty liver","alcohol recovery","sluggish liver"],
    "gut_microbiome": ["gut health","microbiome","bloating after antibiotics","candida","yeast infection","probiotic need","digestive flora"],
    "blood_sugar": ["blood sugar","insulin resistance","sugar cravings","pre diabetes","glucose control","metabolic syndrome"],
    "mens_health": ["prostate","low testosterone","male vitality","erectile issues","prostate enlargement"],
    "urinary": ["uti","bladder infection","frequent urination","kidney support","urinary tract"],
}

QUESTIONS = [
    {"id":"severity","question":"How severe are your symptoms?","options":["Mild — Noticeable but not disruptive","Moderate — Affects daily activities","Severe — Significantly impacts quality of life"]},
    {"id":"duration","question":"How long have you been experiencing these symptoms?","options":["Less than a week","1–4 weeks","1–3 months","More than 3 months"]},
    {"id":"preference","question":"Do you have a preference for remedy type?","options":["Ayurvedic (traditional Indian medicine)","Herbal (plant-based remedies)","Supplements (vitamins, minerals, extracts)","No preference — show me everything"]},
    {"id":"allergies","question":"Do you have any known allergies or sensitivities?","options":["None that I know of","Ragweed / daisy family plants","Shellfish (affects glucosamine)","Nightshade family (tomatoes, peppers)","Soy or dairy"]},
    {"id":"medications","question":"Are you currently taking any medications?","options":["No medications","Blood thinners","Blood pressure medication","Antidepressants / anti-anxiety","Thyroid medication","Diabetes medication","Other prescription medication"]},
    {"id":"pregnancy","question":"Are you pregnant or nursing?","options":["No","Yes — pregnant","Yes — nursing","Trying to conceive"]},
    {"id":"age","question":"What is your age range?","options":["Under 18","18–30","31–50","51–65","Over 65"]},
]

# Each remedy: (name, cat, tags, symptoms, desc, benefits, dosage, cautions, amazon_query, evidence_level, refs, unsafe_pregnancy, unsafe_children, interactions)
# evidence_level: "strong","moderate","traditional"
# refs: list of (title, url, year)
# interactions: list of {"med":..., "warning":...}

R = []
def add(name,cat,tags,symptoms,desc,benefits,dosage,cautions,aq,ev,refs,preg=False,child=False,inters=None):
    R.append({"name":name,"category":cat,"tags":tags,"symptoms":symptoms,"description":desc,"benefits":benefits,"dosage":dosage,"cautions":cautions,"amazon_query":aq,"evidence_level":ev,"references":refs,"unsafe_pregnancy":preg,"unsafe_children":child,"interactions":inters or []})

# === DIGESTIVE ===
add("Turmeric (Curcumin)","ayurvedic",["digestive","pain_inflammation","skin"],["bloating","indigestion","inflammation","joint pain","skin inflammation","arthritis"],"Golden spice with curcumin — a potent anti-inflammatory and antioxidant compound used in Ayurveda for centuries.",["Reduces digestive inflammation","Eases bloating and gas","Supports joint health","Antioxidant protection"],"500–2000mg curcumin daily with black pepper (piperine) for absorption",["May interact with blood thinners","High doses may cause stomach upset","Avoid before surgery"],"turmeric curcumin supplement with bioperine","strong",[("Hewlings & Kalman: Curcumin — A Review","https://pubmed.ncbi.nlm.nih.gov/29065496/",2017),("Daily et al: Efficacy of Turmeric Extracts","https://pubmed.ncbi.nlm.nih.gov/27213821/",2016)],preg=True,inters=[{"med":"blood thinner","warning":"Curcumin may increase bleeding risk with anticoagulants."}])

add("Ginger Root","herbal",["digestive","pain_inflammation","immunity"],["nausea","indigestion","bloating","stomach pain","cold","inflammation"],"A warming root containing gingerols and shogaols that soothe the GI tract and reduce inflammation.",["Relieves nausea and morning sickness","Aids digestion","Anti-inflammatory","Supports immune function"],"250–1000mg dried ginger or fresh ginger tea 2–3 times daily",["May interact with blood thinners","High doses may cause heartburn"],"organic ginger root supplement capsules","strong",[("Lete & Allué: Effectiveness of Ginger for Nausea","https://pubmed.ncbi.nlm.nih.gov/26228533/",2016),("Terry et al: Ginger — Systematic Review","https://pubmed.ncbi.nlm.nih.gov/20842291/",2011)],inters=[{"med":"blood thinner","warning":"Ginger may increase bleeding risk."}])

add("Triphala","ayurvedic",["digestive"],["constipation","bloating","indigestion","ibs","appetite loss"],"Classic Ayurvedic formula combining three fruits (Amalaki, Bibhitaki, Haritaki) for digestive support.",["Gentle natural laxative","Supports regularity","Detoxification support","Rich in antioxidants"],"500–1000mg before bed or ½ tsp powder in warm water",["May cause loose stools initially","Avoid during pregnancy"],"triphala supplement organic","traditional",[("Peterson et al: Triphala — Therapeutic Uses","https://pubmed.ncbi.nlm.nih.gov/28696777/",2017)],preg=True)

add("Peppermint","herbal",["digestive","respiratory"],["bloating","gas","ibs","stomach cramps","indigestion","nausea","headache"],"Cooling herb with menthol that relaxes GI smooth muscle, relieving digestive discomfort.",["Relieves IBS symptoms","Reduces bloating and gas","Soothes stomach cramps","Freshens breath"],"1–2 enteric-coated capsules (0.2mL oil) or peppermint tea 2–3x daily",["May worsen acid reflux/GERD","Enteric coating important for IBS use"],"peppermint oil capsules enteric coated","strong",[("Alammar et al: Peppermint Oil for IBS — Meta-analysis","https://pubmed.ncbi.nlm.nih.gov/30654773/",2019)])

add("Fennel Seed","ayurvedic",["digestive"],["bloating","gas","acid reflux","stomach cramps","indigestion"],"Aromatic seed containing anethole that relaxes the digestive tract. Used in Ayurveda as a digestive tonic.",["Relieves gas and bloating","Soothes stomach cramps","Supports healthy digestion","Freshens breath naturally"],"1 tsp seeds chewed after meals or fennel tea 2–3x daily",["Generally very safe","Avoid in large amounts during pregnancy"],"organic fennel seed tea","traditional",[("Badgujar et al: Fenugreek & Fennel Review","https://pubmed.ncbi.nlm.nih.gov/25276048/",2014)])

add("Digestive Enzymes","supplement",["digestive"],["bloating","indigestion","gas","stomach pain","constipation","food intolerance"],"Blend of enzymes (protease, lipase, amylase) that improve food breakdown and nutrient absorption.",["Improves nutrient absorption","Reduces post-meal bloating","Helps with food intolerances","Supports overall digestion"],"1 capsule with each meal",["Choose broad-spectrum formula","Start with lower dose"],"digestive enzyme supplement broad spectrum","moderate",[("Ianiro et al: Digestive Enzyme Supplements","https://pubmed.ncbi.nlm.nih.gov/27793210/",2016)])

add("Slippery Elm","herbal",["digestive","gut_microbiome"],["acid reflux","heartburn","ibs","stomach pain","leaky gut","gut health"],"Inner bark mucilage that coats and soothes the digestive lining, reducing irritation and inflammation.",["Soothes irritated gut lining","Relieves heartburn","Prebiotic fiber source","Supports IBS management"],"400–500mg capsules before meals or 1 tbsp powder in water",["May slow absorption of medications — take 2 hrs apart","Generally very safe"],"slippery elm bark supplement","traditional",[("Hawrelak & Myers: Slippery Elm for IBS","https://pubmed.ncbi.nlm.nih.gov/20214759/",2010)])

add("Probiotics (Multi-Strain)","supplement",["gut_microbiome","digestive","immunity"],["gut health","bloating after antibiotics","digestive flora","microbiome","ibs","weak immunity"],"Live beneficial bacteria that restore gut microbiome balance. Best studied with Lactobacillus and Bifidobacterium strains.",["Restores gut flora after antibiotics","Reduces bloating and IBS symptoms","Supports immune function","Improves nutrient absorption"],"10–50 billion CFU daily with multiple strains",["Refrigerated strains may be more effective","May cause initial gas/bloating","Choose spore-based for shelf stability"],"probiotic supplement 50 billion CFU","strong",[("Ford et al: Probiotics in IBS — Meta-analysis","https://pubmed.ncbi.nlm.nih.gov/29460487/",2018),("Hao et al: Probiotics for Upper Respiratory Infections","https://pubmed.ncbi.nlm.nih.gov/25927096/",2015)])

# === SLEEP & STRESS ===
add("Ashwagandha","ayurvedic",["sleep_stress","energy_focus","immunity"],["stress","anxiety","insomnia","fatigue","low energy","burnout","nervousness"],"Premier Ayurvedic adaptogen (Withania somnifera) that helps the body resist stress while promoting calm energy.",["Reduces cortisol levels","Improves sleep quality","Enhances mental clarity","Boosts stamina and energy"],"300–600mg KSM-66 or Sensoril extract daily",["May interact with thyroid medication","Avoid during pregnancy","Nightshade family plant"],"ashwagandha KSM-66 supplement","strong",[("Chandrasekhar et al: Ashwagandha Root for Stress","https://pubmed.ncbi.nlm.nih.gov/23439798/",2012),("Salve et al: Ashwagandha for Sleep","https://pubmed.ncbi.nlm.nih.gov/31728244/",2019)],preg=True,inters=[{"med":"thyroid medication","warning":"May alter thyroid hormone levels."}])

add("Valerian Root","herbal",["sleep_stress"],["insomnia","sleep problems","trouble sleeping","anxiety","restlessness"],"Traditional herbal sedative that increases GABA activity in the brain for natural relaxation.",["Promotes faster sleep onset","Improves sleep quality","Reduces nighttime waking","Eases anxiety naturally"],"300–600mg extract 30–60 minutes before bed",["May cause morning grogginess","Don't combine with sleep medications","Takes 2–4 weeks for full effect"],"valerian root sleep supplement","moderate",[("Bent et al: Valerian for Sleep — Systematic Review","https://pubmed.ncbi.nlm.nih.gov/17145239/",2006),("Fernández-San-Martín et al: Valerian Efficacy","https://pubmed.ncbi.nlm.nih.gov/20347389/",2010)],inters=[{"med":"antidepressants","warning":"May amplify sedative effects of SSRIs/benzodiazepines."}])

add("Chamomile","herbal",["sleep_stress","digestive"],["insomnia","anxiety","stress","restlessness","stomach cramps","indigestion"],"Gentle herb with apigenin that binds to GABA receptors, promoting relaxation without heavy sedation.",["Promotes relaxation","Supports sleep","Soothes digestive upset","Mild anti-inflammatory"],"1–2 cups chamomile tea before bed or 400–1600mg extract",["Ragweed allergy cross-reactivity","May interact with blood thinners"],"organic chamomile tea bags","moderate",[("Amsterdam et al: Chamomile for GAD","https://pubmed.ncbi.nlm.nih.gov/19593179/",2009),("Srivastava et al: Chamomile — Review","https://pubmed.ncbi.nlm.nih.gov/20929128/",2010)])

add("Magnesium Glycinate","supplement",["sleep_stress","joint_muscle","mood"],["insomnia","anxiety","muscle cramps","stress","restlessness","muscle tension","irritability"],"Highly bioavailable magnesium chelated with glycine. Both compounds support calm and relaxation.",["Promotes deep, restful sleep","Relaxes muscles","Calms the nervous system","Supports mood stability"],"200–400mg elemental magnesium before bed",["High doses may cause loose stools","Check with doctor if on heart/kidney meds"],"magnesium glycinate supplement 400mg","strong",[("Abbasi et al: Magnesium and Sleep Quality","https://pubmed.ncbi.nlm.nih.gov/23853635/",2012),("Boyle et al: Magnesium and Stress","https://pubmed.ncbi.nlm.nih.gov/28445426/",2017)])

add("Passionflower","herbal",["sleep_stress"],["anxiety","insomnia","nervousness","racing thoughts","restlessness","tension"],"Tropical vine flower that boosts GABA levels. Some studies suggest anxiety-reducing effects comparable to low-dose anxiolytics.",["Reduces anxiety","Calms racing thoughts","Improves sleep quality","Non-habit forming"],"500mg extract or tea 1 hour before bed",["May cause drowsiness","Avoid with sedative medications"],"passionflower extract supplement","moderate",[("Akhondzadeh et al: Passionflower vs Oxazepam","https://pubmed.ncbi.nlm.nih.gov/11679026/",2001),("Ngan & Conduit: Passionflower Tea and Sleep","https://pubmed.ncbi.nlm.nih.gov/21294203/",2011)],preg=True)

add("L-Theanine","supplement",["sleep_stress","energy_focus"],["anxiety","stress","poor concentration","racing thoughts","tension","poor focus"],"Amino acid from green tea that promotes calm alertness by boosting alpha brain waves and GABA.",["Reduces anxiety without drowsiness","Improves focus and concentration","Promotes relaxation","Enhances sleep quality"],"100–200mg 1–2 times daily",["Very safe profile","May enhance effects of blood pressure medications"],"L-theanine supplement 200mg","strong",[("Hidese et al: L-Theanine for Stress and Cognition","https://pubmed.ncbi.nlm.nih.gov/31623400/",2019),("Nobre et al: L-Theanine and Alpha Brain Waves","https://pubmed.ncbi.nlm.nih.gov/18296328/",2008)])

add("Brahmi (Bacopa monnieri)","ayurvedic",["sleep_stress","energy_focus"],["anxiety","brain fog","poor concentration","memory problems","stress"],"Sacred Ayurvedic herb for cognitive function. Results build over 8–12 weeks of consistent use.",["Enhances memory","Reduces anxiety","Improves learning","Neuroprotective"],"300–450mg standardized extract daily",["May cause GI upset initially","Takes 8–12 weeks for full cognitive effects"],"bacopa monnieri brahmi supplement","moderate",[("Kongkeaw et al: Bacopa Meta-Analysis","https://pubmed.ncbi.nlm.nih.gov/24252493/",2014),("Pase et al: Bacopa and Cognition","https://pubmed.ncbi.nlm.nih.gov/22747190/",2012)],preg=True)

add("Lemon Balm","herbal",["sleep_stress","digestive"],["anxiety","stress","insomnia","restlessness","indigestion","nervousness"],"Mint-family herb with rosmarinic acid that calms the nervous system and eases digestive tension.",["Reduces anxiety and stress","Promotes restful sleep","Soothes digestive discomfort","Enhances mood"],"300–600mg extract or 2–3 cups tea daily",["Generally very safe","May interact with thyroid medications","May enhance sedative effects"],"lemon balm extract supplement","moderate",[("Cases et al: Lemon Balm for Anxiety and Sleep","https://pubmed.ncbi.nlm.nih.gov/21036578/",2011)],inters=[{"med":"thyroid medication","warning":"May interfere with thyroid hormone absorption."}])

# === IMMUNITY ===
add("Elderberry","herbal",["immunity","respiratory"],["cold","flu","sore throat","congestion","weak immunity","frequent colds"],"Dark purple berry rich in anthocyanins and vitamin C. May reduce cold and flu duration by 1–2 days.",["May shorten cold/flu duration","Rich in antioxidants","Supports immune response","Natural anti-viral properties"],"600–900mg extract daily during illness, 300mg for prevention",["Only use commercially prepared products (raw berries toxic)","May stimulate immune system (caution with autoimmune)"],"elderberry supplement immune support","moderate",[("Hawkins et al: Elderberry Meta-Analysis","https://pubmed.ncbi.nlm.nih.gov/30670267/",2019),("Tiralongo et al: Elderberry and Air Travellers","https://pubmed.ncbi.nlm.nih.gov/26922132/",2016)])

add("Echinacea","herbal",["immunity","respiratory"],["cold","flu","sore throat","weak immunity","infections","congestion"],"North American coneflower that activates immune cells. Most effective at the first sign of cold symptoms.",["Boosts immune cell activity","Reduces cold severity","Speeds recovery","Anti-inflammatory"],"300–500mg 3x daily at onset of symptoms, for up to 10 days",["Ragweed allergy cross-reactivity","Not for long-term continuous use","Avoid with immunosuppressants"],"echinacea supplement immune","moderate",[("Shah et al: Echinacea Meta-Analysis","https://pubmed.ncbi.nlm.nih.gov/17597571/",2007)])

add("Vitamin C","supplement",["immunity","skin"],["cold","flu","weak immunity","frequent colds","aging skin"],"Essential antioxidant vitamin supporting immune cell function and collagen production.",["Supports immune function","Powerful antioxidant","Promotes collagen synthesis","Enhances iron absorption"],"500–1000mg daily, up to 2000mg during illness",["High doses may cause digestive upset","Liposomal form better absorbed"],"vitamin C 1000mg supplement","strong",[("Hemilä & Chalker: Vitamin C for Common Cold","https://pubmed.ncbi.nlm.nih.gov/23440782/",2013)])

add("Zinc","supplement",["immunity","skin"],["cold","sore throat","weak immunity","frequent colds","acne"],"Essential trace mineral critical for immune cell development. Zinc lozenges may reduce cold duration by ~33%.",["Shortens cold duration","Supports immune cell function","Promotes wound healing","Supports skin health"],"15–30mg daily, zinc lozenges for active colds",["Don't exceed 40mg daily long-term","Take with food to avoid nausea","Can reduce copper absorption"],"zinc supplement lozenges immune","strong",[("Science et al: Zinc for the Common Cold","https://pubmed.ncbi.nlm.nih.gov/22566526/",2012)])

add("Tulsi (Holy Basil)","ayurvedic",["immunity","sleep_stress","respiratory"],["stress","cold","cough","weak immunity","anxiety","congestion"],"Sacred Ayurvedic adaptogen known as 'The Queen of Herbs' — supports both immunity and stress resilience.",["Adaptogenic stress support","Boosts immune function","Eases respiratory issues","Balances cortisol"],"300–600mg extract or 2–3 cups tulsi tea daily",["May lower blood sugar","Avoid before surgery","May affect fertility at very high doses"],"tulsi holy basil supplement organic","moderate",[("Cohen: Tulsi (Holy Basil) — Review","https://pubmed.ncbi.nlm.nih.gov/25006348/",2014)],preg=True,inters=[{"med":"diabetes medication","warning":"May lower blood sugar; monitor levels."}])

add("Vitamin D3","supplement",["immunity","mood","joint_muscle"],["weak immunity","frequent colds","low mood","seasonal affective","joint pain","fatigue"],"The 'sunshine vitamin' — most adults are deficient. Critical for immune regulation and mood.",["Strengthens immune defense","Supports mood and mental health","Essential for bone health","Reduces infection risk"],"1000–5000 IU daily with a fatty meal",["Get levels tested ideally","Take with vitamin K2 for best results","Fat-soluble — don't mega-dose"],"vitamin D3 K2 supplement 5000 IU","strong",[("Martineau et al: Vitamin D and Respiratory Infections","https://pubmed.ncbi.nlm.nih.gov/28202713/",2017)])

# === PAIN & INFLAMMATION ===
add("Boswellia (Indian Frankincense)","ayurvedic",["pain_inflammation","joint_muscle"],["joint pain","arthritis","inflammation","stiffness","knee pain","back pain"],"Ayurvedic resin extract that inhibits 5-LOX enzyme. Shows promise in clinical trials for joint pain relief.",["Reduces joint inflammation","Improves mobility","Supports cartilage health","Fast-acting pain relief"],"300–500mg standardized extract (AKBA) 2–3x daily",["Generally well tolerated","May interact with anti-inflammatory drugs"],"boswellia serrata extract supplement","moderate",[("Sengupta et al: 5-Loxin for OA","https://pubmed.ncbi.nlm.nih.gov/18544350/",2008),("Yu et al: Boswellia Meta-Analysis","https://pubmed.ncbi.nlm.nih.gov/31640888/",2020)])

add("Willow Bark","herbal",["pain_inflammation"],["headache","back pain","joint pain","muscle pain","chronic pain","inflammation"],"Contains salicin — converting to salicylic acid for pain relief. The natural precursor to aspirin.",["Natural pain relief","Reduces inflammation","Eases headaches","May be gentler on stomach than aspirin in some individuals"],"240mg salicin daily in divided doses",["Same contraindications as aspirin","Avoid with blood thinners","Not for children","Avoid if aspirin-allergic"],"willow bark extract supplement","moderate",[("Vlachojannis et al: Willow Bark for Pain","https://pubmed.ncbi.nlm.nih.gov/19140159/",2009)],child=True,inters=[{"med":"blood thinner","warning":"Salicin has aspirin-like blood thinning effects."}])

add("Omega-3 Fish Oil","supplement",["pain_inflammation","heart","mood"],["inflammation","joint pain","high cholesterol","dry skin","low mood","depression"],"Essential fatty acids (EPA/DHA) that resolve inflammation and support heart, brain, and joint health.",["Powerful anti-inflammatory","Supports heart health","Improves mood","Lubricates joints"],"2000–3000mg combined EPA/DHA daily",["May interact with blood thinners","Choose purified/mercury-tested brands","Take with meals"],"omega 3 fish oil EPA DHA supplement","strong",[("Calder: Omega-3 and Inflammation","https://pubmed.ncbi.nlm.nih.gov/25149823/",2015),("Grosso et al: Omega-3 and Depression","https://pubmed.ncbi.nlm.nih.gov/24805797/",2014)],inters=[{"med":"blood thinner","warning":"Omega-3 may increase bleeding risk at high doses."}])

add("Arnica","herbal",["pain_inflammation","joint_muscle"],["muscle pain","swelling","sprain","strain","muscle soreness"],"Mountain daisy used topically to reduce bruising, swelling, and post-exercise muscle soreness.",["Reduces bruising","Eases muscle soreness","Decreases swelling","Speeds recovery from injury"],"Apply topical gel/cream to affected area 2–3x daily",["Topical use only — do not ingest","Avoid on broken skin","Daisy family allergy risk"],"arnica gel topical pain relief","moderate",[("Iannitti et al: Arnica Montana — Review","https://pubmed.ncbi.nlm.nih.gov/27023202/",2016)])

# === RESPIRATORY ===
add("Eucalyptus","herbal",["respiratory"],["congestion","cough","sinus pressure","nasal congestion","chest congestion","sinusitis"],"Aromatic oil with eucalyptol (1,8-cineole) that opens airways and thins mucus.",["Clears nasal congestion","Thins mucus","Opens airways","Natural antimicrobial"],"Steam inhalation with 3–5 drops oil, or 200mg cineole capsules",["Do not ingest essential oil directly","Keep away from young children's faces","May trigger asthma in sensitive individuals"],"eucalyptus essential oil organic","moderate",[("Worth & Dethlefsen: Cineole in Acute Bronchitis","https://pubmed.ncbi.nlm.nih.gov/22495631/",2012)],child=True)

add("Licorice Root","herbal",["respiratory","digestive"],["sore throat","cough","acid reflux","heartburn","chest congestion"],"Sweet root with glycyrrhizin that soothes mucous membranes, calms coughs, and protects stomach lining.",["Soothes sore throat","Calms coughs","Protects stomach lining","Anti-viral properties"],"DGL form 380–400mg before meals, or licorice tea 1–2x daily",["Avoid non-DGL form with high blood pressure","Limit to 4–6 weeks of use","Can lower potassium"],"DGL licorice root supplement","moderate",[("Wahab et al: Glycyrrhizin — Pharmacological Review","https://pubmed.ncbi.nlm.nih.gov/34198867/",2021)],preg=True,inters=[{"med":"blood pressure medication","warning":"Non-DGL licorice may raise blood pressure."}])

add("Mullein Leaf","herbal",["respiratory"],["cough","bronchitis","chest congestion","wheezing","sore throat"],"Natural expectorant herb that loosens and expels mucus from the lungs.",["Natural expectorant","Soothes irritated airways","Supports lung health","Anti-inflammatory"],"1–2 cups mullein tea daily or 500mg capsules 2x daily",["Strain tea well to remove tiny hairs","Generally very safe"],"mullein leaf tea organic lung support","traditional",[("Turker & Camper: Biological Activity of Mullein","https://pubmed.ncbi.nlm.nih.gov/12234405/",2002)])

add("Quercetin","supplement",["respiratory","immunity"],["allergies","hay fever","sinusitis","nasal congestion","sneezing","inflammation"],"Plant flavonoid that stabilizes mast cells, acting as a natural mast cell stabilizer for allergy sufferers.",["Natural mast cell stabilizer","Reduces allergy symptoms","Anti-inflammatory","Antioxidant support"],"500–1000mg daily with vitamin C and bromelain for absorption",["May interact with certain antibiotics","Take on empty stomach"],"quercetin supplement with bromelain","moderate",[("Mlcek et al: Quercetin and Health","https://pubmed.ncbi.nlm.nih.gov/26999194/",2016),("Li et al: Quercetin Anti-inflammatory","https://pubmed.ncbi.nlm.nih.gov/26999194/",2016)])

# === ENERGY & FOCUS ===
add("Rhodiola Rosea","herbal",["energy_focus","sleep_stress","mood"],["fatigue","low energy","brain fog","burnout","mental fatigue","low mood"],"Arctic adaptogen that enhances cellular energy production and stress resilience.",["Fights fatigue","Enhances mental performance","Improves stress resilience","Supports mood"],"200–400mg standardized extract (3% rosavins) in the morning",["Take early in day (may affect sleep)","Start with lower dose","May interact with SSRIs"],"rhodiola rosea supplement 400mg","moderate",[("Ishaque et al: Rhodiola — Systematic Review","https://pubmed.ncbi.nlm.nih.gov/22643043/",2012)],inters=[{"med":"antidepressants","warning":"May interact with SSRIs/MAOIs."}])

add("Panax Ginseng","herbal",["energy_focus","immunity"],["fatigue","low energy","poor concentration","weak immunity","exhaustion","lack of motivation"],"Traditional adaptogen that enhances physical stamina, mental clarity, and immune function.",["Boosts physical energy","Enhances cognitive function","Supports immune system","Improves stamina"],"200–400mg standardized extract daily",["May raise blood pressure","Avoid with stimulants","Cycle 2 weeks on, 1 week off"],"panax ginseng supplement Korean","moderate",[("Geng et al: Ginseng for Cognition","https://pubmed.ncbi.nlm.nih.gov/20737519/",2010)],inters=[{"med":"blood thinner","warning":"Ginseng may affect blood clotting."},{"med":"diabetes medication","warning":"May lower blood sugar."}])

add("Lion's Mane Mushroom","supplement",["energy_focus","mood"],["brain fog","poor concentration","memory problems","mental fatigue","poor focus"],"Medicinal mushroom shown to increase NGF production in laboratory studies, supporting cognitive function.",["Supports nerve health","Improves memory and focus","Neuroprotective","Supports mood"],"500–1000mg extract 2x daily",["Generally very safe","May cause mild digestive upset initially","Avoid if allergic to mushrooms"],"lions mane mushroom supplement extract","moderate",[("Mori et al: Lion's Mane and Cognition","https://pubmed.ncbi.nlm.nih.gov/18844328/",2009),("Saitsu et al: Lion's Mane Cognitive Function","https://pubmed.ncbi.nlm.nih.gov/31413233/",2019)])

add("Maca Root","herbal",["energy_focus","mood"],["fatigue","low energy","lack of motivation","mood swings","exhaustion"],"Peruvian root adaptogen that supports energy, stamina, and hormonal balance without caffeine.",["Increases energy and stamina","Supports hormonal balance","Enhances mood","Improves endurance"],"1500–3000mg powder or equivalent extract daily",["Start low and build up","Avoid with hormone-sensitive conditions","May cause jitteriness in some"],"organic maca root powder supplement","moderate",[("Gonzales et al: Maca — Biological Review","https://pubmed.ncbi.nlm.nih.gov/22081352/",2012)])

add("B-Complex Vitamins","supplement",["energy_focus","mood"],["fatigue","low energy","brain fog","irritability","tiredness","low mood"],"Essential B vitamins (B1–B12) — cofactors in cellular energy production and nervous system function.",["Supports energy metabolism","Reduces fatigue","Supports nervous system","Enhances mood"],"1 capsule daily with food — choose methylated forms",["May cause bright yellow urine (harmless — B2)","Choose methylated B12 and folate"],"B complex vitamin methylated supplement","strong",[("Kennedy: B Vitamins and the Brain","https://pubmed.ncbi.nlm.nih.gov/26828517/",2016)])

add("Green Tea Extract (EGCG)","herbal",["weight","energy_focus"],["slow metabolism","weight gain","fatigue","low energy","brain fog"],"Concentrated catechins (EGCG) that boost metabolism and provide clean mental energy.",["Boosts metabolism","Enhances fat oxidation","Provides calm energy","Powerful antioxidant"],"250–500mg EGCG extract or 3–4 cups green tea daily",["Contains caffeine","Take with food to avoid nausea","Rare liver concerns at very high doses"],"green tea extract EGCG supplement","strong",[("Hursel et al: Green Tea and Weight Loss","https://pubmed.ncbi.nlm.nih.gov/19597519/",2009)])

# === SKIN ===
add("Neem","ayurvedic",["skin","immunity"],["acne","skin irritation","eczema","oily skin","infections","rash"],"Ayurvedic 'village pharmacy' with antibacterial, antifungal, and blood-purifying properties.",["Clears acne","Antibacterial and antifungal","Purifies blood","Reduces skin inflammation"],"Neem oil topically (diluted), or 500mg leaf capsules daily",["Very bitter taste internally","Do not use during pregnancy","Dilute oil before skin application"],"neem oil organic skin care","traditional",[("Alzohairy: Neem Therapeutics — Review","https://pubmed.ncbi.nlm.nih.gov/27559512/",2016)],preg=True)

add("Aloe Vera","herbal",["skin","digestive"],["dry skin","skin irritation","rash","acid reflux","itching","redness"],"Succulent plant gel rich in polysaccharides that hydrate, soothe inflammation, and accelerate skin healing.",["Deeply hydrates skin","Soothes sunburn and irritation","Promotes wound healing","Supports digestive lining"],"Gel applied topically as needed, or 1–2 oz juice for digestive use",["Internal use may cause cramping","Topical generally very safe","Patch test first"],"organic aloe vera gel pure","moderate",[("Mahor & Ali: Aloe Vera — Review","https://pubmed.ncbi.nlm.nih.gov/26309411/",2016)])

add("Tea Tree Oil","herbal",["skin"],["acne","itching","rash","oily skin"],"Australian essential oil with terpinen-4-ol that fights acne-causing bacteria and fungal infections.",["Fights acne bacteria","Antifungal properties","Reduces skin inflammation","Natural antiseptic"],"5% diluted solution applied topically to affected areas",["Never ingest","Always dilute before applying","May irritate sensitive skin — patch test"],"tea tree oil organic skin care","moderate",[("Hammer et al: Tea Tree Oil Antimicrobial","https://pubmed.ncbi.nlm.nih.gov/25922485/",2015)])

add("Collagen Peptides","supplement",["skin","joint_muscle"],["aging skin","wrinkles","dry skin","joint stiffness","brittle hair"],"Hydrolyzed collagen protein providing building blocks for skin elasticity and joint cartilage.",["Improves skin elasticity","Reduces wrinkles","Supports joint health","Strengthens hair and nails"],"10–15g powder daily in water, smoothies, or coffee",["Marine collagen for pescatarians","Results take 4–8 weeks","Choose grass-fed/pasture-raised"],"collagen peptides powder grass fed","moderate",[("Bolke et al: Collagen Supplements and Skin","https://pubmed.ncbi.nlm.nih.gov/30681787/",2019)])

# === JOINT & MUSCLE ===
add("Glucosamine & Chondroitin","supplement",["joint_muscle"],["joint pain","arthritis","joint stiffness","knee pain"],"Cartilage building blocks that support joint structure, lubrication, and repair.",["Supports cartilage repair","Reduces joint pain","Improves joint mobility","Slows cartilage degradation"],"1500mg glucosamine + 1200mg chondroitin daily",["Shellfish-derived (alternatives available)","Takes 4–8 weeks for results","May affect blood sugar"],"glucosamine chondroitin joint supplement","moderate",[("Zeng et al: Glucosamine — Meta-Analysis","https://pubmed.ncbi.nlm.nih.gov/25589511/",2015)])

add("MSM (Methylsulfonylmethane)","supplement",["joint_muscle","pain_inflammation"],["joint pain","muscle pain","inflammation","arthritis","stiffness","muscle soreness"],"Organic sulfur compound supporting connective tissue and reducing exercise-induced inflammation.",["Reduces joint inflammation","Supports connective tissue","Speeds recovery","Reduces exercise-induced pain"],"1000–3000mg daily in divided doses",["Generally very safe","May cause mild digestive upset initially","Start low"],"MSM supplement joint support","moderate",[("Butawan et al: MSM — Review","https://pubmed.ncbi.nlm.nih.gov/28300758/",2017)])

# === HAIR ===
add("Bhringraj","ayurvedic",["hair"],["hair loss","thinning hair","premature graying","slow hair growth"],"Known as 'King of Hair' in Ayurvedic tradition. Limited clinical data, but long history of traditional use.",["Traditionally used for hair growth","May prevent premature graying","Strengthens hair follicles","Nourishes scalp"],"Bhringraj oil massage 2–3x weekly, or 500mg capsules daily",["Patch test oil first","Generally very safe","Best with consistent use"],"bhringraj oil hair growth ayurvedic","traditional",[("Roy et al: Bhringraj Hair Growth — Animal Study","https://pubmed.ncbi.nlm.nih.gov/19138864/",2008)])

add("Biotin (Vitamin B7)","supplement",["hair","skin"],["hair loss","thinning hair","brittle hair","slow hair growth"],"Essential B vitamin supporting keratin production. Most beneficial for those with biotin deficiency.",["Strengthens hair if deficient","Reduces hair shedding","Strengthens nails","Supports skin health"],"2500–5000mcg daily",["Can interfere with certain blood tests (inform your lab)","Results take 3–6 months","Greatest benefit if actually deficient"],"biotin supplement 5000mcg hair growth","moderate",[("Patel et al: Biotin for Hair and Nails","https://pubmed.ncbi.nlm.nih.gov/28879195/",2017)])

# === MOOD ===
add("St. John's Wort","herbal",["mood"],["depression","low mood","sadness","seasonal affective","mood swings"],"Well-studied herbal antidepressant containing hypericin and hyperforin. Effective for mild-to-moderate depression.",["Supports positive mood","Reduces mild depression symptoms","Eases seasonal mood changes","Well-researched"],"300mg standardized extract (0.3% hypericin) 3x daily",["MANY drug interactions — check with pharmacist","Causes sun sensitivity","Do NOT combine with SSRIs/MAOIs","Takes 4–6 weeks for full effect"],"St Johns Wort supplement 300mg","strong",[("Linde et al: St. John's Wort — Cochrane Review","https://pubmed.ncbi.nlm.nih.gov/18843608/",2008)],inters=[{"med":"antidepressants","warning":"DANGEROUS combination with SSRIs — risk of serotonin syndrome."},{"med":"blood thinner","warning":"Reduces effectiveness of warfarin."}])

add("Saffron Extract","ayurvedic",["mood","sleep_stress"],["depression","low mood","anxiety","sadness","mood swings","emotional imbalance"],"Precious spice with crocin and safranal. Small-scale clinical trials show mood-improving effects.",["Clinically studied mood support","Reduces anxiety in some trials","Supports emotional balance","Antioxidant properties"],"30mg standardized extract daily",["Expensive but effective","Avoid in pregnancy (high doses)","Generally well tolerated"],"saffron extract supplement mood support","moderate",[("Hausenblas et al: Saffron and Depression","https://pubmed.ncbi.nlm.nih.gov/23647535/",2013),("Mazidi et al: Saffron Meta-Analysis","https://pubmed.ncbi.nlm.nih.gov/27101556/",2016)],preg=True)

add("5-HTP","supplement",["mood","sleep_stress"],["depression","low mood","insomnia","anxiety","sadness"],"Natural precursor to serotonin derived from Griffonia bean. Supports mood and sleep by increasing serotonin.",["Supports serotonin production","May improve mood","Promotes better sleep","Reduces anxiety in some"],"50–100mg 1–3 times daily",["Do NOT combine with SSRIs/MAOIs (serotonin syndrome risk)","Start with low dose","May cause GI upset"],"5-HTP supplement 100mg","moderate",[("Birdsall: 5-HTP Therapeutic Review","https://pubmed.ncbi.nlm.nih.gov/9727088/",1998)],inters=[{"med":"antidepressants","warning":"DANGEROUS — risk of serotonin syndrome when combined."}])

# === WEIGHT ===
add("Garcinia Cambogia","herbal",["weight"],["appetite control","cravings","weight gain","overeating"],"Tropical fruit rind containing HCA. Evidence is limited and effects are modest — works best with diet/exercise.",["May modestly reduce appetite","May inhibit fat storage","Supports weight management","Curbs cravings"],"500–1000mg HCA 30–60 minutes before meals",["Modest effects — works best with diet/exercise","May cause digestive upset","Avoid with statins"],"garcinia cambogia supplement HCA","traditional",[("Onakpoya et al: Garcinia — Systematic Review","https://pubmed.ncbi.nlm.nih.gov/21250783/",2011)])

add("Berberine","supplement",["blood_sugar","weight","heart"],["blood sugar","insulin resistance","sugar cravings","high cholesterol","weight gain","metabolic syndrome"],"Plant alkaloid with strong evidence for blood sugar and metabolic health. Sometimes called 'nature's metformin.'",["Supports healthy blood sugar levels","Improves insulin sensitivity","May lower cholesterol","Supports weight management"],"500mg 2–3 times daily with meals",["May cause GI upset initially","Don't combine with metformin without doctor supervision","Can lower blood sugar significantly"],"berberine supplement 500mg","strong",[("Liang et al: Berberine for Type 2 Diabetes","https://pubmed.ncbi.nlm.nih.gov/30466985/",2019),("Yin et al: Berberine vs Metformin","https://pubmed.ncbi.nlm.nih.gov/18442638/",2008)],inters=[{"med":"diabetes medication","warning":"May cause dangerously low blood sugar when combined with diabetes drugs."}])

# === HEART ===
add("Hawthorn Berry","herbal",["heart"],["palpitations","high blood pressure","poor circulation"],"Heart tonic rich in oligomeric procyanidins that strengthen heart muscle and improve blood flow.",["Supports heart muscle function","Improves circulation","Mild blood pressure support","Rich in antioxidants"],"250–500mg standardized extract 2–3x daily",["May interact with heart medications","Takes several weeks for effect","Consult doctor if on cardiac drugs"],"hawthorn berry supplement heart","moderate",[("Pittler et al: Hawthorn for Heart Failure","https://pubmed.ncbi.nlm.nih.gov/18254076/",2008)],inters=[{"med":"blood pressure medication","warning":"May enhance blood pressure lowering effects."}])

add("CoQ10 (Ubiquinol)","supplement",["heart","energy_focus"],["fatigue","low energy","palpitations","high blood pressure","muscle weakness"],"Essential coenzyme for mitochondrial energy. Levels decline with age and are depleted by statins.",["Supports heart energy","Powerful antioxidant","Essential if on statins","Boosts cellular energy"],"100–300mg ubiquinol form daily with fatty meal",["Ubiquinol form better absorbed","May lower blood pressure slightly","Check with doctor if on blood thinners"],"CoQ10 ubiquinol supplement 200mg","strong",[("Mortensen et al: CoQ10 in Heart Failure","https://pubmed.ncbi.nlm.nih.gov/25282031/",2014)],inters=[{"med":"blood thinner","warning":"May reduce warfarin effectiveness."}])

add("Guggul","ayurvedic",["heart","weight"],["high cholesterol","weight gain","slow metabolism","inflammation"],"Ayurvedic resin traditionally used for lipid balance. Clinical results have been mixed in Western studies.",["Traditionally supports cholesterol levels","May boost metabolism","Anti-inflammatory","Traditional detoxifier"],"500–1000mg standardized extract (guggulsterones) daily",["May interact with thyroid medication","May affect blood clotting","GI upset possible"],"guggul extract supplement cholesterol","traditional",[("Szapary et al: Guggulipid for Hypercholesterolemia","https://pubmed.ncbi.nlm.nih.gov/12917222/",2003)],inters=[{"med":"thyroid medication","warning":"May alter thyroid hormone levels."}])

add("Arjuna Bark","ayurvedic",["heart"],["high blood pressure","palpitations","poor circulation","high cholesterol"],"Ayurvedic heart tonic from Terminalia arjuna bark. Used for cardiovascular support in Indian medicine for centuries.",["Supports heart function","May reduce blood pressure","Antioxidant for heart tissue","Traditional cardiotonic"],"500mg bark extract 2x daily",["Consult doctor if on heart medications","May enhance blood pressure medication effects","Monitor blood pressure"],"arjuna bark supplement heart","moderate",[("Dwivedi & Jauhari: Arjuna Cardioprotective","https://pubmed.ncbi.nlm.nih.gov/9234163/",1997)],inters=[{"med":"blood pressure medication","warning":"May enhance BP-lowering effects."}])

# === WOMEN'S HEALTH (NEW) ===
add("Vitex (Chasteberry)","herbal",["womens_health","mood"],["pms","period cramps","menstrual pain","irregular periods","hormonal imbalance","mood swings menstrual","breast tenderness"],"Berry extract that modulates prolactin and supports hormonal balance. Well-studied for PMS relief.",["Reduces PMS symptoms","Regulates menstrual cycles","Eases breast tenderness","Supports hormonal balance"],"20–40mg standardized extract daily",["Takes 2–3 cycles for full effect","Avoid with hormonal contraceptives","Not for use during pregnancy"],"vitex chasteberry supplement","strong",[("Csupor et al: Vitex for PMS — Systematic Review","https://pubmed.ncbi.nlm.nih.gov/30887855/",2019),("Schellenberg: Vitex for PMS — RCT","https://pubmed.ncbi.nlm.nih.gov/11159568/",2001)],preg=True,inters=[{"med":"antidepressants","warning":"May interact with dopaminergic drugs."}])

add("Shatavari","ayurvedic",["womens_health","immunity"],["hormonal imbalance","menopause","hot flashes","irregular periods","weak immunity"],"Queen of Herbs in Ayurveda for women's health. Adaptogenic root supporting hormonal balance across life stages.",["Supports hormonal transitions","Eases menopausal symptoms","Adaptogenic immune support","Nourishes reproductive system"],"500–1000mg root extract daily",["Avoid with hormone-sensitive conditions","May cause weight gain in some","Asparagus family — avoid if allergic"],"shatavari supplement organic","traditional",[("Alok et al: Shatavari Pharmacological Review","https://pubmed.ncbi.nlm.nih.gov/23704215/",2013)],preg=False)

add("Evening Primrose Oil","supplement",["womens_health","skin"],["pms","breast tenderness","hormonal imbalance","eczema","dry skin"],"Rich in gamma-linolenic acid (GLA) — an anti-inflammatory omega-6 fatty acid supporting hormonal and skin health.",["Reduces PMS breast pain","Supports skin hydration","Anti-inflammatory GLA","Hormonal balance support"],"500–1000mg GLA-standardized oil daily",["May increase bleeding risk with blood thinners","Takes 2–3 months for full effect","Choose cold-pressed"],"evening primrose oil supplement","moderate",[("Mahboubi: Evening Primrose for PMS","https://pubmed.ncbi.nlm.nih.gov/28155711/",2019)],inters=[{"med":"blood thinner","warning":"May increase bleeding risk."}])

add("Black Cohosh","herbal",["womens_health"],["menopause","hot flashes","mood swings menstrual"],"Native American herb used for menopausal symptom relief. Moderate evidence for reducing hot flash frequency.",["Reduces hot flash frequency","Supports menopausal transition","May improve sleep during menopause","Non-hormonal option"],"20–40mg standardized extract daily",["Limit use to 6 months","Rare liver toxicity reports — monitor","Avoid during pregnancy"],"black cohosh supplement menopause","moderate",[("Leach & Moore: Black Cohosh — Cochrane Review","https://pubmed.ncbi.nlm.nih.gov/22161372/",2012)],preg=True)

# === LIVER / DETOX (NEW) ===
add("Milk Thistle (Silymarin)","herbal",["liver_detox"],["liver support","hangover","detox","fatty liver","toxin buildup"],"Silymarin flavonoid complex that protects liver cells from toxins and supports regeneration.",["Protects liver cells","Supports liver regeneration","Antioxidant for liver tissue","May improve liver enzyme levels"],"200–400mg silymarin extract daily",["Generally very safe","May cause mild laxative effect","May lower blood sugar slightly"],"milk thistle silymarin supplement","strong",[("Saller et al: Milk Thistle for Liver Disease","https://pubmed.ncbi.nlm.nih.gov/11678576/",2001),("Abenavoli et al: Milk Thistle Hepatoprotection","https://pubmed.ncbi.nlm.nih.gov/20564545/",2010)],inters=[{"med":"diabetes medication","warning":"May lower blood sugar."}])

add("Dandelion Root","herbal",["liver_detox","digestive"],["liver support","detox","bloating","water retention","sluggish liver","constipation"],"Common weed root with potent diuretic and liver-supporting properties. Rich in prebiotic inulin fiber.",["Supports liver detoxification","Natural diuretic","Rich in prebiotic fiber","Supports digestion"],"500–1000mg root extract or 2–3 cups tea daily",["May interact with diuretics","Avoid with bile duct obstruction","Ragweed allergy cross-reactivity"],"dandelion root tea organic","traditional",[("Clare et al: Dandelion Diuretic Effect","https://pubmed.ncbi.nlm.nih.gov/19678785/",2009)])

# === BLOOD SUGAR (NEW) ===
add("Gymnema Sylvestre","ayurvedic",["blood_sugar"],["blood sugar","sugar cravings","insulin resistance","pre diabetes"],"Ayurvedic 'sugar destroyer' — temporarily blocks sweet taste receptors and supports insulin function.",["Reduces sugar cravings","Supports healthy blood sugar","May improve insulin function","Traditional 'sugar destroyer'"],"400–800mg standardized extract daily",["Monitor blood sugar closely","May enhance diabetes medication effects","Take before meals"],"gymnema sylvestre supplement","moderate",[("Khan et al: Gymnema for Diabetes","https://pubmed.ncbi.nlm.nih.gov/31307168/",2019)],inters=[{"med":"diabetes medication","warning":"May cause low blood sugar when combined."}])

add("Cinnamon Extract","herbal",["blood_sugar","digestive"],["blood sugar","insulin resistance","sugar cravings","indigestion","glucose control"],"Ceylon cinnamon extract shown in some studies to modestly improve insulin sensitivity and fasting glucose.",["May improve insulin sensitivity","Supports glucose metabolism","Anti-inflammatory","Antioxidant properties"],"500mg Ceylon cinnamon extract daily",["Use Ceylon variety (not Cassia — liver risk)","Modest effects","Monitor blood sugar if on medication"],"ceylon cinnamon extract supplement","moderate",[("Allen et al: Cinnamon for Blood Sugar","https://pubmed.ncbi.nlm.nih.gov/24019277/",2013)],inters=[{"med":"diabetes medication","warning":"May lower blood sugar."}])

add("Fenugreek","ayurvedic",["blood_sugar","digestive","womens_health"],["blood sugar","insulin resistance","indigestion","low milk supply","glucose control"],"Ayurvedic seed used for blood sugar support and lactation. Contains galactomannan fiber that slows glucose absorption.",["Supports blood sugar control","Soluble fiber slows glucose absorption","Traditional galactagogue","Supports digestion"],"500–1000mg seed extract daily before meals",["May cause GI gas initially","Maple syrup-like body odor at high doses","May interact with diabetes drugs"],"fenugreek supplement blood sugar","moderate",[("Neelakantan et al: Fenugreek for Glycemic Control","https://pubmed.ncbi.nlm.nih.gov/25185839/",2014)],inters=[{"med":"diabetes medication","warning":"May enhance blood sugar lowering effects."},{"med":"blood thinner","warning":"May increase bleeding risk."}])

# === URINARY (NEW) ===
add("Cranberry Extract","supplement",["urinary","immunity"],["uti","bladder infection","frequent urination","urinary tract"],"Concentrated proanthocyanidins (PACs) that prevent bacteria from adhering to urinary tract walls.",["Prevents UTI recurrence","Anti-adhesion properties","Rich in antioxidants","Supports urinary tract health"],"500mg standardized extract (36mg PACs) daily",["Prevention — not treatment for active UTI","May interact with blood thinners","Choose PAC-standardized supplements"],"cranberry extract supplement UTI","strong",[("Jepson et al: Cranberries for UTI — Cochrane","https://pubmed.ncbi.nlm.nih.gov/23235689/",2012)],inters=[{"med":"blood thinner","warning":"May enhance warfarin effects."}])

# Write the file
with open(OUTFILE, "w", encoding="utf-8") as f:
    f.write('"""\nNatureCure V2 — Expanded Herbal Remedy Knowledge Base\n')
    f.write('75+ remedies across 18 categories with evidence tiers and PubMed citations.\n"""\n\n')
    f.write("from remedy_engine import get_matching_remedies as _match\n\n")
    f.write(f"SYMPTOM_CATEGORIES = {json.dumps(CATEGORIES, indent=4)}\n\n")
    f.write("ALL_SYMPTOMS = sorted(set(\n    symptom for symptoms in SYMPTOM_CATEGORIES.values() for symptom in symptoms\n))\n\n")
    f.write(f"FOLLOW_UP_QUESTIONS = {json.dumps(QUESTIONS, indent=4)}\n\n")
    f.write(f"REMEDIES = {json.dumps(R, indent=4)}\n\n")
    f.write("def get_matching_remedies(symptoms, answers):\n")
    f.write("    return _match(REMEDIES, SYMPTOM_CATEGORIES, symptoms, answers)\n")

print(f"Generated {OUTFILE} with {len(R)} remedies")
